spring.application.name=Employee

# H2 Database (Development)
spring.datasource.url=jdbc:h2:mem:employeedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Actuator Endpoints
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

# Logging
logging.level.root=INFO
logging.level.org.myapp.employee=DEBUG
logging.level.software.amazon.awssdk=DEBUG

# AWS S3
aws.s3.bucket=blob-documents-uploads
aws.s3.region=ap-south-1
aws.accessKeyId=${AWS_ACCESS_KEY_ID:your_aws_access_key_id}
aws.secretKey=${AWS_SECRET_ACCESS_KEY:}${AWS_SECRET_ACCESS_KEY:your_aws_secret_access_key}

# Async thread pool
spring.task.execution.pool.core-size=2
spring.task.execution.pool.max-size=5
spring.task.execution.pool.queue-capacity=100

# Oracle Database Container Image
docker.image.oracle=container-registry.oracle.com/database/free:latest

